<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Character;


class CharactersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $characters = [
            ['name' => '茅森月歌', 'unit_id' => 1, 'seraphim_code' => 'あたしの伝説はこれから始まる', 'seraph' => 'BvaveBlue', 'first_person' => 'あたし', 'birthday' => '6月24日', 'height' => '159cm', 'birthplace' => '神奈川', 'voice_actor' => '楠木ともり/Vo.XAI', 'character_description' => '伝説的ロックバンド『She is
            Legend』の元ギター＆ボーカル。作詞作曲もこなし、メジャーデビューアルバムはその年の新人賞を総なめ。天才という言葉を欲しいままにした。ひたすら音楽が好きで、31Aの六人で新生『She
            is Legend』を結成してしまう。脳天気で、仲間思いで、時たま根性を見せる。',],
            ['name' => '和泉ユキ', 'unit_id' => 1, 'seraphim_code' => 'Hello World', 'seraph' => 'RapidFire', 'first_person' => 'あたし', 'birthday' => '9月17日', 'height' => '160cm', 'birthplace' => '新潟', 'voice_actor' => '前川涼子', 'character_description' => 'ハッカー集団『オーキッド』に所属していた、第三次世界大戦を防いだ実績を持つ天才ハッカー。ボケだらけの31Aの中では唯一の常識人で、ツッコミ役を一手に担う。茅森が所属していた伝説的バンド『She
            is Legend』のファン。セラフ部隊に入ってからは茅森に振り回されつつも親身に支える。',],
            ['name' => '逢川めぐみ', 'unit_id' => 1, 'seraphim_code' => '救世主様のお出ましや', 'seraph' => 'Clavis', 'first_person' => 'うち', 'birthday' => '10月28日', 'height' => '159cm', 'birthplace' => '大阪', 'voice_actor' => '伊波杏樹', 'character_description' => '関西出身の勝気なサイキック少女。超能力を扱えるが、その力は未知数。というか、セラフ部隊に入ってからは特に役に立っていない。しかし自分が世界を救う救世主であると信じている。同世代で天才としてもてはやされていた茅森に対して勝手にライバル意識を持っている。',],
            ['name' => '東城つかさ', 'unit_id' => 1, 'seraphim_code' => '真実は一つと限らない', 'seraph' => 'SupremeEdge', 'first_person' => 'わたし', 'birthday' => '2月14日', 'height' => '163cm', 'birthplace' => '東京', 'voice_actor' => '天海由梨奈', 'character_description' => '完璧な外見を持つ、自称エリート諜報員。しかし、どこからどう見ても中身はポンコツ諜報員。ただ、役に立たない情報だけは無駄に詳しい。同じ31Aの朝倉可憐に美肌のコツを教えては、悦に入っている。',],
            ['name' => '朝倉可憐', 'unit_id' => 1, 'seraphim_code' => '呼吸をするように息の根を止める', 'seraph' => 'GlitterShadow', 'first_person' => '表:あたし/裏:ワシ', 'birthday' => '45118', 'height' => '158cm', 'birthplace' => '栃木', 'voice_actor' => '芹澤優 /Vo.鈴木このみ', 'character_description' => 'FPSが得意なゲーマー少女。その容姿通りの可愛らしい性格。ゲームをプレイし続けられる理由から、片手で食べられるジャンクフードを好む。新生『She is
            Legend』でツインボーカルの一翼を担う。しかし裏の人格は恐ろしい殺人鬼。',],
            ['name' => '國見タマ', 'unit_id' => 1, 'seraphim_code' => '天下一品', 'seraph' => 'PhantomWeaver', 'first_person' => '私', 'birthday' => '7月11日', 'height' => '137cm', 'birthplace' => '長崎', 'voice_actor' => '古賀葵', 'character_description' => 'こんな見た目で戦艦の元艦長。オホーツク海で敗れ去った。天然ボケな性格だが、自覚はない。いつも庇ってくれる同じ31Aの逢川めぐみを慕っている。背が低いことをコンプレックスに感じている。',],
            ['name' => '蒼井えりか', 'unit_id' => 2, 'seraphim_code' => 'どうか安寧な記憶を', 'seraph' => 'ShootingStar', 'first_person' => '私/蒼井', 'birthday' => '7月7日', 'height' => '158cm', 'birthplace' => '埼玉', 'voice_actor' => '宮下早紀', 'character_description' => 'テストで必ず１００点を取れる天才少女。３１Ｂの部隊長だが、自分に自信がなくいつもおどおどとしている。同じ３１Ｂのビャッコの存在だけが心のよりどころ。よくぽかーんと呆けてしまう。',],
            ['name' => '水瀬いちご', 'unit_id' => 2, 'seraphim_code' => 'インフェルノに焼かれな', 'seraph' => 'GuiltyCracker', 'first_person' => 'あたし', 'birthday' => '1月15日', 'height' => '172cm', 'birthplace' => '愛知', 'voice_actor' => '愛美', 'character_description' => '水瀬すももと姉妹の殺し屋。いちごは姉。言動はがさつで、すぐひとに銃口を向けるおっかない人物。好きなスポーツは野球。好きな食べ物は野菜スティック。',],
            ['name' => '水瀬すもも', 'unit_id' => 2, 'seraphim_code' => 'ニブルヘイムで凍えろにゃ', 'seraph' => 'RainnyLull', 'first_person' => 'すもも', 'birthday' => '9月6日', 'height' => '154cm', 'birthplace' => '愛知', 'voice_actor' => '小路裕夕', 'character_description' => '水瀬いちごと姉妹の殺し屋。すももは妹。殺し屋として天賦の才を持つ。雰囲気はアンニュイに映るが、キレさせると危険。好きな食べ物は５円チョコ。',],
            ['name' => '樋口聖華', 'unit_id' => 2, 'seraphim_code' => '新鮮な「死」を見せてくれ', 'seraph' => 'FatalNull', 'first_person' => '私', 'birthday' => '11月8日', 'height' => '151cm', 'birthplace' => '滋賀', 'voice_actor' => '山根綺', 'character_description' => '基地内の科学技術研究所に務める研究員。セラフにも詳しい。天才科学者であることは間違いないが、その熱意は狂気的。生命の「死」すらにも興味を持ち、そのため、自らセラフ部隊員となり、前線へも繰り出している。',],
            ['name' => '柊木梢', 'unit_id' => 2, 'seraphim_code' => '眠れ、イノセントレクイエム', 'seraph' => 'MANA', 'first_person' => 'あたし', 'birthday' => '3月18日', 'height' => '157cm', 'birthplace' => '青森', 'voice_actor' => '小澤亜李', 'character_description' => '幽霊を見ることができる少女。眼帯で隠された左目を解放すると、幽霊を成仏させることが出来る。やや中二病。',],
            ['name' => 'ビャッコ', 'unit_id' => 2, 'seraphim_code' => 'ヴァゥーーーーーーー！', 'seraph' => 'Vrtra', 'first_person' => '-', 'birthday' => '4月8日', 'height' => '-', 'birthplace' => '岩手', 'voice_actor' => '-', 'character_description' => '軍の実験の末、セラフと唯一適合した動物。非常に賢いが、人見知り。蒼井にだけは心を許している。カルパスが好物。',],
            ['name' => '山脇・ボン・イヴァール', 'unit_id' => 3, 'seraphim_code' => 'この世界は私の実験台よ', 'seraph' => 'LoveReaper', 'first_person' => '私', 'birthday' => '8月25日', 'height' => '156cm', 'birthplace' => '熊本', 'voice_actor' => '千本木彩花', 'character_description' => '豊後と一緒に世界征服を企むマッドサイエンティスト。ただし自称。３１Ｃの部隊長であり、茅森たちと同期。Ａを冠する部隊がその世代のエリートとして扱われるため、Ａを奪おうと茅森たちに挑戦状を叩きつける。高圧的で、血気盛んだが、本当は友達思いの優しい子。',],
            ['name' => '桜庭星羅', 'unit_id' => 3, 'seraphim_code' => '星の導きがあらんことを', 'seraph' => 'FutureOracle', 'first_person' => '私', 'birthday' => '6月29日', 'height' => '171cm', 'birthplace' => '長野', 'voice_actor' => '田澤茉純', 'character_description' => '占星術で未来を視る占い師。よく恋愛占いを勧めてくる。占い道具である水晶がないと何も出来ない。落ち着いた物腰から告げられる言葉には不思議な説得力がある。なお、占いの的中率は53％。',],
            ['name' => '天音巫呼', 'unit_id' => 3, 'seraphim_code' => '忘却は死、追憶に生きよ', 'seraph' => 'MarginalWizard', 'first_person' => 'わし', 'birthday' => '7月22日', 'height' => '129cm', 'birthplace' => '富山', 'voice_actor' => '宮崎珠子', 'character_description' => '不老不死を追い求め、色々な薬を作っている。その過程で生まれた様々な薬は、病を治し世界中に貢献してきた。自身を稀代の魔術師と自称している。ダボダボのローブを羽織り、ロリっ子に見えるが本人は決して認めない。',],
            ['name' => '豊後弥生', 'unit_id' => 3, 'seraphim_code' => '世界征服開始でゲス！', 'seraph' => 'ScarletValet', 'first_person' => 'あちき', 'birthday' => '4月1日', 'height' => '121cm', 'birthplace' => '熊本', 'voice_actor' => '白花恋香', 'character_description' => 'マッドサイエンティスト山脇のしもべで、一緒に世界征服を企む少女。体は小さく、精神年齢は低いが、運動能力だけは抜群。キャンサーとも充分に渡り合える。語尾が「ゲス」。好戦的なセリフばかり吐くが、なぜだかα波を引き起こす癒やし系キャラである。',],
            ['name' => '神崎アーデルハイド', 'unit_id' => 3, 'seraphim_code' => 'イッツニンジャショータイム！', 'seraph' => '9ー', 'first_person' => '拙者', 'birthday' => '2月22日', 'height' => '160cm', 'birthplace' => 'ドイツ・ベルリン', 'voice_actor' => '稗田寧々', 'character_description' => 'ドイツからやって来た、目立ちたがり屋の忍ばない忍者。忍者への強い憧れから独学で猛特訓して忍術を会得。基地の至るとこで忍術を披露している。一定以上注目され続けると、言語中枢が乱れて興奮し始める。',],
            ['name' => '佐月マリ', 'unit_id' => 3, 'seraphim_code' => '全滅のご注文承りました', 'seraph' => 'FortuneGear', 'first_person' => 'わたし', 'birthday' => '2月7日', 'height' => '150cm', 'birthplace' => '三重', 'voice_actor' => '宮本侑芽', 'character_description' => '基地のすべてのショップに務めるスーパー店員。ひとりではなく、複数居るのでは？と思われるほど。しかも戦っても強い。男兄弟の中で育ったため、たまに言動が粗暴になる。３１Ｃの精神的支柱になりたいと日々頑張っている。',],
            ['name' => '二階堂三郷', 'unit_id' => 4, 'seraphim_code' => '天元、取ったり', 'seraph' => '-', 'first_person' => '私', 'birthday' => '6月6日', 'height' => '163cm', 'birthplace' => '奈良', 'voice_actor' => '奈波果林', 'character_description' => '囲碁の天才棋士で前代未聞の５０連勝を成した最年少名人にして、未来の棋聖と期待されている。"天才"と呼ばれた棋士だった祖父のことを強く尊敬している。威厳のある言動を心がけているが、勝負に勝ったり好きな食べ物を前にしたりすると少女らしい顔を見せる。褒められ慣れていないのか、割と照れやすい。',],
            ['name' => '石井色葉', 'unit_id' => 4, 'seraphim_code' => '世界をあーし色に染め上げるッス', 'seraph' => '-', 'first_person' => 'あーし', 'birthday' => '5月26日', 'height' => '156cm', 'birthplace' => '和歌山', 'voice_actor' => '桑原由気', 'character_description' => '生まれつき色が常人とは違う知覚で見えているアーティスト。色がわからないことをビハインドとはとらえておらず、自分だけの世界を描くことに熱中している。色彩に関することに限らず、様々な面で独創的な価値観を持つ。そのため、作品も極めて独創的な表現に偏っている。',],
            ['name' => '命吹雪', 'unit_id' => 4, 'seraphim_code' => 'Make a Change...Kill Yourself', 'seraph' => '-', 'first_person' => 'あたし', 'birthday' => '3月4日', 'height' => '154cm', 'birthplace' => '北海道', 'voice_actor' => '浅見春那', 'character_description' => '聴いていると死にたくなってくる危険な音楽、デプレッシブブラックメタルを愛する。途中までは普通のメタルをやっていたが、デプレッシブブラックメタルを始めた途端、メンバーは去って行った。以降、ドラムだけは打ち込みで、ギター、ベース、ボーカル、ミックス、マスタリングまですべてひとりでこなすことに。多作だが、一番売れたアルバムでも２１枚。',],
            ['name' => '室伏理沙', 'unit_id' => 4, 'seraphim_code' => '常に上を向いていきましょう', 'seraph' => '-', 'first_person' => '私', 'birthday' => '5月12日', 'height' => '168cm', 'birthplace' => '山口', 'voice_actor' => '中村桜', 'character_description' => '全身から母性が溢れ出すお姉さん。バレーボール部のエリートとしてスカウトされた。なんでも受け止める包容力を持つ。その包容力の前では普段からどれだけ気を張っている者であろうと甘えずにはいられない。お母さん扱いされると「あらあら」「うふふ」と言いつつたしなめる。どこまで本気で怒っているのかわからない。彼女の前では、誰であろうと幼児返りを起こす。',],
            ['name' => '伊達朱里', 'unit_id' => 4, 'seraphim_code' => 'エースをねらわれるな', 'seraph' => '-', 'first_person' => 'わたし', 'birthday' => '10月21日', 'height' => '154cm', 'birthplace' => '兵庫', 'voice_actor' => '大野柚布子', 'character_description' => 'テニス部のエリートとしてスカウトされた…が、自己評価が異様に低いネガティブ少女。練習ではしっかり動けるのだが、大会では練習時の実力が発揮できないのか、戦績はゼロ。それでも、テニスに対する姿勢は（低姿勢ながらも）真剣。側にいると、彼女のネガティブ空間に引き込まれることも。',],
            ['name' => '瑞原あいな', 'unit_id' => 4, 'seraphim_code' => 'どこまでも潜るさー', 'seraph' => '-', 'first_person' => 'あいな', 'birthday' => '11月2日', 'height' => '141cm', 'birthplace' => '静岡', 'voice_actor' => '星谷美緒', 'character_description' => '幼い見た目とは裏腹に、海洋生物学の博士号を持ち、第一線で活躍する研究者。外見相応にのほほんとした雰囲気の少女。海洋生物の中でも、深海魚に興味を持ち、外見、生態、味のすべてに惚れ込んでいる。勤勉だが、海洋生物学以外の学問は苦手。',],
            ['name' => '大島一千子', 'unit_id' => 5, 'seraphim_code' => '大島家長女ここにあり', 'seraph' => 'HeroicFulcrum', 'first_person' => 'わたし', 'birthday' => '11月29日', 'height' => '160cm', 'birthplace' => '福岡', 'voice_actor' => '日向葵', 'character_description' => '貧乏な家庭で育った六つ子の長女。一家のまとめ役。貧乏で苦しくても、自分だけはいつも笑顔で明るい家族を作ろうと努力してきた。長女であることに強い責任感を持つ。家族が安定した収入を得られるよう、軍の中で出世したいというハングリー精神を持っている。',],
            ['name' => '大島二以奈', 'unit_id' => 5, 'seraphim_code' => 'うぬぼれ、大いに結構', 'seraph' => 'IdolPlanet', 'first_person' => '私', 'birthday' => '11月29日', 'height' => '162cm', 'birthplace' => '福岡', 'voice_actor' => '金子彩花', 'character_description' => '貧乏な家庭で育った六つ子の次女。一家のおしゃれ担当。地方雑誌の読者モデルで得た収入を家に収め、仕事先で譲ってもらった服を家族に配っている。おしゃれが好きだが、貧乏なので普段の服装は実用性重視。自分の容姿に自信を持ち、自分磨きを欠かさない。',],
            ['name' => '大島三野里', 'unit_id' => 5, 'seraphim_code' => 'はいよ、戦力お待たせ', 'seraph' => 'LightBeat', 'first_person' => 'ぼく', 'birthday' => '11月29日', 'height' => '158cm', 'birthplace' => '福岡', 'voice_actor' => '中島由貴', 'character_description' => '貧乏な家庭で育った六つ子の三女。一家のムードメーカーかつては朝は新聞配達、放課後はデリバリーサービスのバイトで一家の生計を助けていた。セラフ本部でも、スケボーに乗って様々な荷物を配達している。最速で配達をするためなら無茶なルートでもスケボーで駆け抜ける。',],
            ['name' => '大島四ツ葉', 'unit_id' => 5, 'seraphim_code' => '頑張らない！', 'seraph' => 'LazyCritter', 'first_person' => 'あたい', 'birthday' => '11月29日', 'height' => '139cm', 'birthplace' => '福岡', 'voice_actor' => '内山茉莉', 'character_description' => '貧乏な家庭で育った六つ子の四女。一家のサボり担当。姉妹の中で唯一、欠片もハングリー精神がない少女。引きこもりだが貧乏なので、ひたすら寝るのが趣味。でも天使の寝顔。セラフ部隊に入ってからはゲームにコーラに贅沢三昧。',],
            ['name' => '大島五十鈴', 'unit_id' => 5, 'seraphim_code' => 'オープン・ザ・ロック', 'seraph' => 'GloomSeeker', 'first_person' => 'あたし', 'birthday' => '11月29日', 'height' => '154cm', 'birthplace' => '福岡', 'voice_actor' => '中野さいま', 'character_description' => '貧乏な家庭で育った六つ子の五女。一家のトラブルメーカー。いたずら好きで家族を困らせることもしばしば。鍵開けを得意とし、錠をまるで生き物を扱うかのように開けていく。本人曰く、女の子の扱いも得意。',],
            ['name' => '大島六宇亜', 'unit_id' => 5, 'seraphim_code' => 'あたしはこけたりしない', 'seraph' => 'FlavorRain', 'first_person' => 'あたし', 'birthday' => '11月29日', 'height' => '157cm', 'birthplace' => '福岡', 'voice_actor' => '福島美里衣', 'character_description' => '貧乏な家庭で育った六つ子の六女。一家の癒やし担当。身体を動かすことが好きで、走ることだけは誰にも負けたくない。コミュ力が高く、誰とでも友達になれる。自分の身体を苛め抜くことを追求し、時にそれに悦びを感じることも…。',],
            ['name' => '柳美音', 'unit_id' => 6, 'seraphim_code' => 'お嬢様の仰せのままに', 'seraph' => 'LuxuryThorn', 'first_person' => '私', 'birthday' => '4月13日', 'height' => '170cm', 'birthplace' => '宮城', 'voice_actor' => '鳥越まあや', 'character_description' => '３１Ｆの部隊長であると同時に、同部隊の丸山奏多に仕える執事。執事としての能力は非常に高く、家事や雑務を完璧にこなすだけでなく、戦闘能力も高い。やんちゃな丸山のサポートで気苦労が多いが、真っ直ぐな心を持つ丸山を誰よりも尊敬し、信頼している。丸山の危機には敏感で少し過保護。丸山のためなら冷酷にもなる。',],
            ['name' => '丸山奏多', 'unit_id' => 6, 'seraphim_code' => 'センスの違いを見せてやる', 'seraph' => 'CryFlower', 'first_person' => 'ボク', 'birthday' => '10月1日', 'height' => '139cm', 'birthplace' => '宮城', 'voice_actor' => '河野ひより', 'character_description' => '様々な分野のセンスの塊。センスに強いこだわりを持つ。名家の一人娘だが、少年らしい言動が目立つ。がさつな言動をお付きの執事である柳に窘められることもあるが、本人は気にしていない。本人は認めないが、柳に依存しきっている。',],
            ['name' => '華村詩紀', 'unit_id' => 6, 'seraphim_code' => 'ここが私のステージだ', 'seraph' => 'FuryStringer', 'first_person' => '私', 'birthday' => '3月25日', 'height' => '172cm', 'birthplace' => '山梨', 'voice_actor' => '時澤香保里', 'character_description' => 'クラシックをこよなく愛する指揮者。良い音楽をつくるためには感情を知る必要があり、感情を知るためには色恋沙汰をたくさん経験してしかるべき、という信念を持っている。恋多き事を恥ずかしく思わない信条から、大勢の少女たちを自室に招いている。夢はセラフ部隊のみんなで、自分中心の楽団（ハレム）を作ること。',],
            ['name' => '松岡チロル', 'unit_id' => 6, 'seraphim_code' => 'どんな戦場でもおまかせあれ', 'seraph' => 'PopnGore', 'first_person' => 'ボク', 'birthday' => '4月26日', 'height' => '150cm', 'birthplace' => '高知', 'voice_actor' => '小島ゆい', 'character_description' => '様々なアクションをこなすスタントウーマン。生傷の絶えない体は、過酷なスタントを「無事に」こなしてきた証。裏方という役目に誇りを持っており、求められればどんなことにも気前よく力を貸す。ちょっとした演技もこなすことができて、ノリも良い。',],
            ['name' => '夏目祈', 'unit_id' => 6, 'seraphim_code' => '相伝の一閃、いざ', 'seraph' => 'Ren', 'first_person' => '私', 'birthday' => '8月15日', 'height' => '154cm', 'birthplace' => '東京', 'voice_actor' => '築山苑佳', 'character_description' => '江戸時代から脈々と続く、罪人を処刑する剣技を受け継いだ少女。常に重々しい雰囲気を放ち、人を寄せ付けようとしない。基本、誰とも会話しようとせず、目も合わせようとしない。実はただの口下手なのかもしれない。',],
            ['name' => '黒沢真希', 'unit_id' => 6, 'seraphim_code' => 'うちの背中についてきんさい！', 'seraph' => 'AmazingExecuter', 'first_person' => 'うち', 'birthday' => '11月22日', 'height' => '163cm', 'birthplace' => '広島', 'voice_actor' => '黒瀬ゆうこ', 'character_description' => 'たった１年で全国制覇を成し遂げた暴走族の総長。道を共にする仲間を第一に考え、義理と人情に生きる。気合の入った人物を見つけると、自分のチームに勧誘しようとする。「広島焼き」を断じて認めない。',],
            ['name' => 'キャロル・リーパー', 'unit_id' => 7, 'seraphim_code' => 'Ready,steady,die', 'seraph' => 'IronMaiden', 'first_person' => 'アタシ', 'birthday' => '8月2日', 'height' => '164cm', 'birthplace' => 'アメリカ・ニューヨーク', 'voice_actor' => '八巻アンナ', 'character_description' => 'アメリカ・ニューヨーク支部から派遣されてきたセラフ隊員。３１Ｘの部隊長。常に自前の衣装やマスクをつけ、ヒーローじみた言動をとる。鎌型のセラフを用い、ダークヒーロー系のキャラ付けで自分を印象付けようとしている。ツッコミもアメリカン。',],
            ['name' => '李映夏', 'unit_id' => 7, 'seraphim_code' => '我が覇道を見よ', 'seraph' => 'TacticalWheel', 'first_person' => 'わらわ', 'birthday' => '12月14日', 'height' => '158cm', 'birthplace' => '中国・北京', 'voice_actor' => '東郷しえり', 'character_description' => '中国・北京支部から派遣されてきたセラフ隊員。諸葛孔明の子孫であることを誇りにしており、自身も抜きんでた軍略を備えている。孔明への尊敬の念が少々空回っているところがある。三国志の故事に関わるとガードが緩くなる。',],
            ['name' => 'アイリーン・レドメイン', 'unit_id' => 7, 'seraphim_code' => '真実は1つだけ', 'seraph' => 'Citadel of Wisdom', 'first_person' => 'あたし', 'birthday' => '10月7日', 'height' => '143cm', 'birthplace' => 'イギリス・ロンドン', 'voice_actor' => 'Marika', 'character_description' => 'イギリス・ロンドン支部から派遣されてきた名探偵にして、セラフ隊員。観察力や推理力は鋭く、推理が当たると得意げになる。名探偵は自分の素性を明かさないものだとして、偽名を使っているらしい。たいがいの奇行も「名探偵なので」で押し通す。',],
            ['name' => 'ヴリティカ・バラクリシュナン', 'unit_id' => 7, 'seraphim_code' => '数こそ万物の根源', 'seraph' => '∞', 'first_person' => 'ワタシ', 'birthday' => '1月26日', 'height' => '131cm', 'birthplace' => 'インド/ニューデリー', 'voice_actor' => '小坂井祐莉絵', 'character_description' => 'インド・ニューデリー支部から派遣されてきたセラフ隊員。史上最年少で数学オリンピックにて金を取った少女。考え事をしているのか、ぼうっとしているのか、見抜くのが難しい。会話の最中に数字の世界に没頭し、何事もなかったかのように会話に戻ってくる。',],
            ['name' => 'マリア・デ・アンジェリス', 'unit_id' => 7, 'seraphim_code' => 'さあ子羊ども懺悔の時間だ', 'seraph' => 'BloodySage', 'first_person' => 'オレ', 'birthday' => '2月26日', 'height' => '170cm', 'birthplace' => 'イタリア・ローマ', 'voice_actor' => '亜月優音', 'character_description' => 'イタリア・ローマ支部から派遣されてきたセラフ隊員。シスター服を身にまとい、それに不釣り合いな斧を持ち歩いている。華奢な見た目とは裏腹に非常に怪力。ガラが悪くすぐ暴言を吐くが、挨拶などの礼儀作法を大切にしている面もある。',],
            ['name' => 'シャルロッタ・スコポフスカヤ', 'unit_id' => 7, 'seraphim_code' => 'シャロを愛して', 'seraph' => 'InnocentStinger', 'first_person' => 'シャロ', 'birthday' => '5月7日', 'height' => '150cm', 'birthplace' => 'ロシア・モスクワ', 'voice_actor' => '会沢紗弥', 'character_description' => 'ロシア・モスクワ支部から派遣されてきたセラフ隊員。数々の恐ろしい戦場を生き残ってきたが、目立った功績はない。なぜかいつも独り生き残っている不思議な少女。マヌルネコのぬいぐるみをいつも抱えている。',],
            ['name' => '白河ユイナ', 'unit_id' => 8, 'seraphim_code' => 'ノブレス・オブリージュ', 'seraph' => 'Temperance', 'first_person' => '私', 'birthday' => '1月6日', 'height' => '164cm', 'birthplace' => '不明', 'voice_actor' => '花守ゆみり', 'character_description' => '仲間からの信頼が厚く、頼られる存在。真面目で誠実だが、親しみやすさも兼ね備えている。思いもよらないことを言われるとうろたえてしまう可愛いらしい一面を持つ。茅森の相談に乗り続けることにより、それがどんどん引き出されていく。',],
            ['name' => '月城最中', 'unit_id' => 8, 'seraphim_code' => '風林火山', 'seraph' => 'Nue', 'first_person' => '我', 'birthday' => '12月1日', 'height' => '170cm', 'birthplace' => '鹿児島', 'voice_actor' => '松本沙羅', 'character_description' => '現役セラフ部隊で最強と呼ばれる戦士。武士のような佇まいで、強者の貫禄がある。飲み物や汁ものを作るのが得意。かつての戦いで失った親友とふたりでカフェを開くことが夢だった。',],
            ['name' => '桐生美也', 'unit_id' => 8, 'seraphim_code' => '鳴らせ退魔の弦！', 'seraph' => 'Rinka', 'first_person' => 'わたくし', 'birthday' => '1月5日', 'height' => '156cm', 'birthplace' => '京都', 'voice_actor' => '大西亜玖璃', 'character_description' => '弓道の才に恵まれ「百年にひとりの逸材」として日本代表に選ばれたこともあった。日本の伝統文化を愛するあまり、「日本伝統文化保存同好会」を立ち上げ、精力的に活動するようになったが、未だ会員は自分ひとり。和服を羽織ったり、お面をつけていたりと非常に個性的な外見をしている。普段は丁寧で物腰柔らかだが、テンションがあがると非常にグイグイくるタイプ。',],
            ['name' => '菅原千恵', 'unit_id' => 8, 'seraphim_code' => 'カワイイは最強ですわ', 'seraph' => 'SweetWhisp', 'first_person' => 'あたくし', 'birthday' => '12月25日', 'height' => '152cm', 'birthplace' => '群馬', 'voice_actor' => '根本京里', 'character_description' => '顔つきと口調がコロコロ変わる。穏やかなときは上品だが、キレると非常に狂暴。ロリータ服を愛し、日々仲間を増やそうとしている。同部隊の桐生とは、ひとつの文化を愛する同士として、気が合う。',],
            ['name' => '小笠原緋雨', 'unit_id' => 8, 'seraphim_code' => '寄らば斬る！', 'seraph' => 'Kazabana', 'first_person' => 'わたし', 'birthday' => '3月21日', 'height' => '138cm', 'birthplace' => '千葉', 'voice_actor' => '嶺内ともみ、櫻井海亜', 'character_description' => '剣の道に生きる３０Ｇ部隊最年少の少女。孤高の剣士を気取る。自分が年下なのを気にしていて、ことあるごとに先輩風を吹かすところがある。３分以上戦えないという設定を自分に課しているおかしな子。剣術以外のことで褒められ慣れていないので、すぐにテンパる。',],
            ['name' => '蔵里見', 'unit_id' => 8, 'seraphim_code' => '五穀豊穣、刈り入れ時だね！', 'seraph' => 'TwilightEmber', 'first_person' => 'あたい', 'birthday' => '6月18日', 'height' => '172cm', 'birthplace' => '秋田', 'voice_actor' => '井澤美香子', 'character_description' => 'お米に対して尋常ならざる愛着と技術を持っている。トロピカル巻きやノスタルジックにぎりなるグルメを生み出し、基地内でも人気を博している。月城の戦いのサポート役を買って出ている。余裕たっぷりを装っているが、茅森に関わると、翻弄されまくり、キャラすらもぶれる。',],
        ];
        Character::truncate();
        foreach ($characters as $character) {
            Character::create($character);
        }
    }
}
